name: NestJS template workflow
on: [ push ]
env:
  SERVICE_NAME: nestjs-template
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          check-latest: true

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # Build & Publish a Docker Image | Main Branch Only
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: github.ref == 'refs/heads/main'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repo Name for Registry
        if: github.ref == 'refs/heads/main'
        run: |
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/${{ env.SERVICE_NAME }}:latest